openapi: "3.0.0"
info:
  title: "Intranet Bookshelf API"
  description: "REST API communication between the front-end (React) to back-end (Undetermine)."
  contact:
    name: "J. Trpka"
    url: "https://www.github.com/jtrpka0912"
    email: "jtrpka0912@gmail.com"
  version: "1.0.0"
servers:
  - url: "http://localhost:3001/api/v1"
    description: "Development Server"
components:
  schemas:
    File:
      type: object
      description: Data representing an ebook inside the bookshelf.
      properties:
        id:
          type: integer
          description: The primary key.
          minimum: 1
        type:
          type: string
          description: Is this a book, magazine, or comic book?
          enum:
          - book
          - magazine
          - comicbook
        name:
          type: string
          description: Name of the ebook.
        path:
          type: string
          description: Path to the ebook in the NAS.
        cover:
          type: string
          description: Path to the image, created in backend, of the ebook.
        didRead:
          type: boolean
          description: Did the user read the ebook.
      required:
        - id
        - type
        - name
        - path
    Book:
      allOf:
      - $ref: '#/components/schemas/File'
      - type: object
        properties:
          author:
            type: string
            description: The author of the ebook book.
    Magazine:
      allOf:
        - $ref: '#/components/schemas/File'
        - type: object
          properties:
            issue:
              type: integer
              description: The issue number of the ebook magazine.
  examples:
    File:
      summary: eBook Book Example
      description: A simple example of an ebook Book example.
      value:
        id: 1
        type: book
        name: Journey to the West
        path: /path/to/ebook/journey-to-the-west.pdf
        cover: /path/to/ebook/cover/journey-to-the-west.jpg
        didRead: false
