openapi: "3.0.0"
info:
  title: "Intranet Bookshelf API"
  description: "REST API communication between the front-end (React) to back-end (Undetermine)."
  contact:
    name: "J. Trpka"
    url: "https://www.github.com/jtrpka0912"
    email: "jtrpka0912@gmail.com"
  version: "1.0.0"
servers:
  - url: "http://localhost:3000/api/v1"
    description: "Development Server"
components:
  schemas:
    File:
      type: object
      description: Data representing an ebook inside the bookshelf.
      properties:
        id:
          type: integer
          description: The primary key.
        type:
          type: string
          description: Is this a book, magazine, or comic book?
          enum:
          - book
          - magazine
          - comicbook
        name:
          type: string
          description: Name of the ebook.
        path:
          type: string
          description: Path to the ebook in the NAS.
        cover:
          type: string
          description: Path to the image, created in backend, of the ebook.
        didRead:
          type: boolean
          description: Did the user read the ebook.
      required:
        - id
        - type
        - name
        - path